### ISSUE TITLE
ArgumentException: Requested value 'uk_monzo_flex' was not found.

### ISSUE THREAD

**Issue by benbristow** [JoeEcob/monzo.net#5]
![image](https://user-images.githubusercontent.com/1159378/219478818-4d9323a2-f095-4957-b81a-fc01e76cd758.png)

Seems like this was fixed with #3 but hasn't been published to Nuget.org as the last version was published in April before this PR.

https://www.nuget.org/packages/Monzo#versions-body-tab

**Comment by JoeEcob** [comment]
Cheers Ben - this has been fixed now
